CREATE TABLE PUBLIC.TL_TEMPLATE_DETAIL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    CONTENT CLOB NOT NULL,
    SUFFIX VARCHAR(20),
    DIR VARCHAR(20),
    TEMPLATE_ID BIGINT NOT NULL,
    CREATE_TIME DATE NOT NULL,
    UPDATE_TIME DATE,
    DELETE_TIME DATE,
    CONSTRAINT TL_TEMPLATE_DETAIL_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_A ON PUBLIC.TL_TEMPLATE_DETAIL (ID);