DROP TABLE IF EXISTS TL_TEMPLATE;
CREATE TABLE IF NOT EXISTS TL_TEMPLATE(
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id' PRIMARY KEY,
    name VARCHAR(20) NOT NULL COMMENT '名称',
    create_time TIMESTAMP WITH TIME ZONE NOT NULL COMMENT '创建时间',
    update_time TIMESTAMP WITH TIME ZONE COMMENT '更新时间',
    delete_time TIMESTAMP WITH TIME ZONE COMMENT '删除时间'
);

DROP TABLE IF EXISTS TL_TEMPLATE_DETAIL;
CREATE TABLE PUBLIC.TL_TEMPLATE_DETAIL (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	CONTENT CLOB NOT NULL,
	FILE_NAME VARCHAR(100),
	DIR VARCHAR(20),
	TEMPLATE_ID BIGINT NOT NULL,
	DELETE_TIME TIMESTAMP WITH TIME ZONE,
	CREATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
	UPDATE_TIME TIMESTAMP WITH TIME ZONE
);