spring:
  application:
    name: generate-test
  datasource:
    url: jdbc:h2:~/chun_generate;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: root
    password: root
    driverClassName: org.h2.Driver
